sudo: false

language: objective-c

branches:
  only:
    - cef_2357
    - cef_2454

xcode_project: CEF.swift.xcodeproj
xcode_scheme: CEF.swift
osx_image: xcode7
xcode_sdk: macosx10.11 

before_install:
  - brew update
  - brew install p7zip
  - brew install jq
  - brew install cmake

install: ./scripts/setup.sh

script: xcodebuild clean build -project CEF.swift.xcodeproj -scheme CEF.swift
